config/routes.rb
Rails.application.routes.draw do
  resources :inscriptions
  resources :meets
  resources :events
  resources :speakers
  resources :themes
  resources :categories
  devise_for :users

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  has_many :meets
  has_many :users, through: :inscriptions

  paginates_per 3
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /events or /events.json
  def index
    @events = Event.all
    @events = Event.order(:name).page params[:page]
    @events = @events.where(["events.name LIKE :filter", :filter => ('%'+ params[:filter] + '%')]) unless params[:filter].blank?
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :start_date, :end_date, :cost, :category_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='container'>
    <div class="form-group">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>

    <div class="form-group">
      <%= form.label :start_date %> <br>
      <%= form.date_select :start_date %>
    </div>

    <div class="form-group">
      <%= form.label :end_date %> <br>
      <%= form.date_select :end_date %>
    </div>

    <div class="form-group">
      <%= form.label :cost %> <br>
      <%= form.text_field :cost %>
    </div>

    <div class="form-group">
      <%= form.label :category_id %> <br>
      <%= form.collection_select(:category_id, Category.all, :id, :name)   %>
    </div>

    <div class="actions"> <br>
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', events_path, class: 'btn btn-secondary' %>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<br>
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<br>
<h1>Events</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Cost</th>
      <th scope="col">Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <% if event.end_date >= Time.now %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= event.cost %></td>
            <td><%= event.category.name %></td>
            <td><%= link_to 'Show', event %></td>
            <td><%= link_to 'Edit', edit_event_path(event) if can? :edit, Event %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Inscription', new_inscription_path if can? :create, Inscription %></td>
          </tr>
      <% end %>
    <% end %>
    </table>
    <%= paginate @events %>
    <table class="table table-striped">
      <% if current_user.admin? %>
        <h1>Expired Events</h1>
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">End Date</th>
            <th scope="col">Cost</th>
            <th scope="col">Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <% @events.each do |event| %>
            <% if event.end_date <= Time.now %>
              <tr>
                <td><%= event.name %></td>
                <td><%= event.end_date %></td>
                <td><%= event.cost %></td>
                <td><%= event.category.name %></td>
                <td><%= link_to 'Show', event %></td>
                <td><%= link_to 'Edit', edit_event_path(event) if not can? :edit, Event %></td>
                <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td><%= link_to 'Inscription', new_inscription_path if not can? :create, Inscription %></td>
              </tr>
            <% end %>
          <% end %>
      <% end %>
    </table>
  </tbody>
<br>
<%= link_to 'New Event', new_event_path, class: 'btn btn-primary' if can? :create, Event %>


    

app/views/events/new.html.erb
<br><h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @event.cost %>
</p>

<p>
  <strong>Category:</strong>
  <%= @event.category.name %>
</p>

<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' if can? :edit, Event %> |
<%= link_to 'Back', events_path, class: 'btn btn-secondary' %>