config/routes.rb
Rails.application.routes.draw do
  resources :inscriptions
  resources :meets
  resources :events
  resources :speakers
  resources :themes
  resources :categories
  devise_for :users

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meet.rb
class Meet < ApplicationRecord
  belongs_to :event, dependent: :destroy 
  belongs_to :speaker,dependent: :destroy 
  
  paginates_per 3
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: %i[ show edit update destroy ]
  load_and_authorize_resource
  # GET /meets or /meets.json
  def index
    @meets = Meet.all
    @meets = Meet.order(:name).page params[:page]
  end

  # GET /meets/1 or /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets or /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: "Meet was successfully created." }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1 or /meets/1.json
  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: "Meet was successfully updated." }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1 or /meets/1.json
  def destroy
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: "Meet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meet_params
      params.require(:meet).permit(:name, :date, :start_time, :end_time, :event_id, :speaker_id)
    end
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/meets/_form.html.erb
<%= form_with(model: meet) do |form| %>
  <% if meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
        <% meet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %> <br>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :start_time %> <br>
    <%= form.time_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %> <br>
    <%= form.time_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :event_id %> <br>
    <%= form.collection_select(:event_id, Event.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :speaker_id %> <br>
    <%= form.collection_select(:speaker_id, Speaker.all, :id, :last_name)%>
  </div>

  <div class="actions"> <br>
    <%= form.submit class: 'btn btn-primary' if can? :create, Meet %>
    <%= link_to 'Back', meets_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/meets/edit.html.erb
<br>
<h1>Editing Meet</h1>

<%= render 'form', meet: @meet %>

app/views/meets/index.html.erb
<br>

<h1>Meets</h1>

<table>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col">Start time</th>
        <th scope="col">End time</th>
        <th scope="col">Event</th>
        <th scope="col">Speaker</th>
        <th colspan="3"> </th>
      </tr>
    </thead>
    <tbody>
      <% @meets.each do |meet| %>
        <tr>
            <td scope="row"><%= meet.name %></td>
            <td scope="row"><%= meet.date %></td>
            <td scope="row"><%= meet.start_time %></td>
            <td scope="row"><%= meet.end_time %></td>
            <td scope="row"><%= meet.event.name %></td>
            <td scope="row"><%= meet.speaker.last_name %></td>
            <td><%= link_to 'Show', meet %></td>  
            <td><%= link_to 'Edit', edit_meet_path(meet) %></td>
            <td><%= link_to 'Destroy', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
  <%= paginate @meets %>
<br>

<%= link_to 'New Meet', new_meet_path, class: 'btn btn-primary'%>

app/views/meets/new.html.erb
<br>
<h1>New Meet</h1>

<%= render 'form', meet: @meet %>

app/views/meets/show.html.erb
<br>

<p>
  <strong>Name:</strong>
  <%= @meet.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @meet.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meet.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meet.end_time %>
</p>

<p>
  <strong>Event:</strong>
  <%= @meet.event.name %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @meet.speaker.last_name %>
</p>

<%= link_to 'Edit', edit_meet_path(@meet), class: 'btn btn-primary' if can? :edit, Meet %> |
<%= link_to 'Back', meets_path, class: 'btn btn-secondary'%>