config/routes.rb
Rails.application.routes.draw do
  resources :inscriptions
  resources :meets
  resources :events
  resources :speakers
  resources :themes
  resources :categories
  devise_for :users

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<header class="p-3 bg-dark text-white">

    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <%= link_to "Events", events_path, class: 'nav-link px-2 text-white' if can? :index, Event %>
          <%= link_to "Categories", categories_path, class: 'nav-link px-2 text-white' if can? :index, Category %>
          <%= link_to "Themes", themes_path, class: 'nav-link px-2 text-white' if can? :index, Theme %>
          <%= link_to "Meets", meets_path, class: 'nav-link px-2 text-white' if can? :index, Meet %>
          <%= link_to "Speakers", speakers_path, class: 'nav-link px-2 text-white' if can? :index, Speaker %>
          <%= link_to "Inscriptions", inscriptions_path, class: 'nav-link px-2 text-white' if can? :index, Inscription %>
      </ul>
    
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="/events" method="get">         
            <input type="text" class="form-control form-control-dark" placeholder="Search Events" name="filter" value="" aria-label="Search"/>
        </form>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3"></form>
          
          <div class="text-end">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-outline-light me-2' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-warning'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-outline-light me-2'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'btn btn-warning'  %>
            <% end %>
          </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventos</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'layouts/navbar' %>
    
    <div class='container'>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>